---
- name: restart apache
  ansible.builtin.service:
    name: "{{ apache_service_name }}"
    state: restarted
    enabled: yes

- name: wait for apache
  ansible.builtin.wait_for:
    port: "{{ apache_port }}"
    delay: 5
    timeout: 60

- name: validate apache
  uri:
    url: "http://localhost:{{ apache_port }}"
    return_content: yes
    status_code: 200
    timeout: 10
  register: validation
  until: validation.status == 200
  retries: 3
  delay: 5
  ignore_errors: yes