---
- name: Check Nginx status
  ansible.builtin.service_facts:
  register: service_status

- name: Verify Nginx is listening
  ansible.builtin.shell: "ss -tulnp | grep nginx || true"
  register: nginx_ports
  changed_when: false

- name: Restart Nginx if needed
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
  when: >
    ('nginx' not in service_status.services) or
    (nginx_ports.stdout | length == 0) or
    (emergency_restart | bool)
  notify:
    - wait for nginx
    - validate nginx

- name: Ensure default page exists
  ansible.builtin.template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: nginx
    group: nginx
    mode: 0644