---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Install Apache
  include_tasks: install.yml
  tags: install

- name: Configure Apache
  include_tasks: configure.yml
  tags: configure

- name: Manage Apache service
  include_tasks: service.yml
  tags: service

- name: Validate Apache functionality
  include_tasks: validate.yml
  tags: validate