---
- name: Ensure web services are running properly
  hosts: all
  become: true
  any_errors_fatal: false

  pre_tasks:
    - name: Verify Ansible meets minimum version
      ansible.builtin.assert:
        that: ansible_version.full is version_compare('2.12', '>=')
        msg: "Ansible 2.12 or higher required"

  tasks:
    - name: Include web server role based on inventory group
      include_role:
        name: "{{ 'apache' if 'apache_servers' in group_names else 'nginx' }}"
      vars:
        emergency_restart: false